version: '2.1'

services:
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE="phalcon_demo"
